### PR TITLE
Add support for stm32f401.

### PR DESCRIPTION
**Pull request by jkristell**
Add support for the stm32f401 MCU.

Tested with my BSP repo for the nucleo-f401re board.  

https://github.com/jkristell/nucleo-f401re

### CODE REVIEW

**Comment by therealprof** [comment]
@jkristell Recapitulating my earlier look reminded me that something is missing: I would expect the STM32F401 clock limits and setup also to be part of the first commit. Can you please make sure that the frequency limit of 84MHz is obeyed and that everything (well, serial for now) works nicely up to that speed?

**Comment by jkristell** [comment]
@therealprof I will do that. As everything just worked when I tested with my board running from the different clocks, I didn't even look at the setup code. But I will take a look and add code and documentation for that. Thanks!

**Comment by therealprof** [comment]
Uhm, why did you close this and delete the branch?

**Comment by jkristell** [comment]
I will send you a new pull request soon. Messed this up a bit. Still not used to github :).

**Pull request closed without merging**
