### PR TITLE
Add a config struct to control uart async data framing

### PR DESCRIPTION
**Pull request by timbod7**
This is proposed for comments. Assuming it looks ok, I will document and implement onthe other usarts.

### CODE REVIEW

**Comment by timbod7** [comment]
> The approach should be independent of any MCU specific flags

I didn't see the need for this given that the _construction_ of the serial interface is entirely MCU dependent (ie you specify the actual USART and pins to use).

Are you suggesting I should make a local copy of the STOPW enum, and them map back to the MCU specific one?

> There should be some builder functions to make up the configuration

I'm new to rust, and am largely unaware of preferred coding patterns. Given that the internal implementation is unlikely to change, what's the reason to prefer a builder over a simple struct with a corresponding default value?

**Comment by timbod7** [comment]
Thanks for the answers - I'll follow up with another commit.

> You chose to use stm32::usart6::cr2::STOPW to initialise USART2 

Is that wrong? I think the MCU crate generated by svd2rust only generates the types for usart6, and then reuses them for the other compatible USARTs.

**Comment by therealprof** [comment]
> Is that wrong? I think the MCU crate generated by svd2rust only generates the types for usart6, and then reuses them for the other compatible USARTs.

Actually you're right, I was reading that as capital `USART6`. However the UARTs have their set of registers produced as `uart4` and those are not compatible with the `usart6` registers and values, so my point still stands. ;)

**Comment by timbod7** [comment]
Hopefully close to what you had in mind?

**Comment by therealprof** [comment]
Looks good on first glance, except that it's not using the builder pattern. ;)

In your approach you'd do something like:
```
let mut config = Config::new(115_200);
config.set_parity_even();
config.set_wordlength_9();
...
let mut serial = usart2(..., config);
```

OTOH the builder pattern returns takes ownership of the structure and then returns the modified structure back to the caller, so you'd end up with:
```
let config = Config::new(115_200).set_parity_even(). set_wordlength_9();
...
let mut serial = usart2(..., config);
```
or you could just do it in a single `let mut serial` line, too:
```
let mut serial = usart2(..., Config::new(115_200).set_parity_even(). set_wordlength_9());
```

I'd probably get rid of the `set_`, too, for brevity sake.

I'll have to inspect the rest of it a bit closer later and give it a test run.

PS: What are we going to do about the other U(S)ARTs? I'm afraid we'll either have to multiply the changes in or we'll have to macrofy it first.

**Comment by timbod7** [comment]
> What are we going to do about the other U(S)ARTs? I'm afraid we'll either have to multiply the changes 

I assumed that `serial.rs` wasn't using macros for a reason.

Once the changes on USART2 looked ok, I intended to multiply the changes.

**Comment by therealprof** [comment]
> I assumed that serial.rs wasn't using macros for a reason.

My laziness. ;)

**Comment by timbod7** [comment]
I thought that the new method that took all non defaultable parameters was
preferable. But happy to change it to a default instance with an arbitrary
baud rate.

**Comment by therealprof** [comment]
Whether to supply parameters to new or not is a preference thing. Providing a `Default` implementation is almost always a good thing and there's a clippy lint happily complaining if you have a `new` method but no `default` method.

**Comment by timbod7** [comment]
On switching back to a default trait rather than a `new()` method it seems a little harder to use... 

This:

```
        let config : serial::config::Config = Default::default()
            .baudrate(100_000.bps())
            .parity_even()
            .wordlength_9()
            .stopbits(serial::config::StopBits::STOP2);
```
doesn't build:

```
  --> src/main.rs:60:47
   |
60 |         let config : serial::config::Config = Default::default()
   |                                               ^^^^^^^^^^^^^^^^^^ cannot infer type for `Self`
   |
   = note: type must be known at this point
```

I seem to need to write:

```
        let config : serial::config::Config = Default::default();
        let config = config
            .baudrate(100_000.bps())
            .parity_even()
            .wordlength_9()
            .stopbits(serial::config::StopBits::STOP2);
```

is there a better way?

**Comment by timbod7** [comment]
I was still expecting to duplicate to the other USARTs....

**Comment by therealprof** [comment]
Try:
```
let config = serial::config::Config::default();
```

**Comment by timbod7** [comment]
BTW. Thanks for your guidance along the way. This is pretty much my first rust code.

**Comment by therealprof** [comment]
@timbod7 Do that in another PR and earn yourself a Hacktoberfest shirt. ;)

**Pull request merged**
